version: '3.9'
services:
  snut:
    image: 'corentinth/snut:latest'
    container_name: snut
    ports:
      - '3000:3000'
    environment:
      - DATABASE_PATH=/app/db/db.sqlite
    volumes:
      - '.db:/app/db'
    restart: unless-stopped
