version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    restart: unless-stopped
